apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesStrategicMerge:
- deployment.yaml
- configmap.yaml
- service.yaml
resources:
- hpa.yaml
- ingress.yaml
- secret.yaml

namespace: default
images:
- name: vuongnv/reactjs-api-gateway
  newTag: '2.0'
