apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: demo
spec:
  #replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
       containers:
        - name: demo
          envFrom:
          - secretRef:
              name: demo-secret
          - configMapRef:
              name: demo-configmap
          # livenessProbe:
          #   httpGet:
          #     path: /liveness ## light het muc co the, chi can tra ve 200 la dc
          #     port: 80
          #   initialDelaySeconds: 40
          #   timeoutSeconds: 10
          #   failureThreshold: 10
          # readinessProbe:
          #   initialDelaySeconds: 30
          #   timeoutSeconds: 5
          #   httpGet:
          #     path: /hc ## check dependency 3rd (rabbitmq postgres ) lien tuc, fail se ko nhan traffic
          #     port: 80
