apiVersion: v1
kind: Secret
metadata:
  name: file-secret
type: Opaque
data:
  StorageSetting__AccessKey: M2JGalBNUDhVczJUVFh0VA==
  StorageSetting__SecretKey: aGlWZFRMNXhIV3FpMzBGTDhaRmxNVzFpdUJucUM3d3M=