version: "3.4"

services:
  fileservice:
    image: "vuongnv/reactjs-file-service:1.0"
    container_name: "fileservice"
    hostname: "fileservice"
    network_mode: bridge
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80      
      - ServiceConfig__serviceAddress=http://172.17.0.1:8081      
      - TZ=Asia/Ho_Chi_Minh
    ports:
      - "8081:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
